### ISSUE TITLE
handle module name conflict with ffmpeg-python

### ISSUE THREAD

**Issue by lucemia** [lucemia/typed-ffmpeg#401]
```
from setuptools import setup

setup(
    name='your_package',
    version='1.0.0',
    install_requires=[
        # Your other dependencies
    ],
    extras_require={
        'full': ['another_dependency'],
    },
    # Use an incompatibility marker for the conflicting package
    install_requires=[
        'incompatible_package<0',  # Prevents any version of incompatible_package from being installed
    ],
)
```

**Comment by abingham** [comment]
Do you have a plan to resolve this? I'm facing an issue where one of my transitive dependencies uses `ffmpeg-python`, so I can't use `typed-ffmpeg` at the same time.

**Comment by lucemia** [comment]
Thank you for bringing this up! I hadn’t considered this conflict before, as ffmpeg-python and typed-ffmpeg offer almost identical functionality. However, I understand your case is a real issue. To resolve this, I plan to release a mirror package with a different module name to avoid any conflicts between the two. I’ll keep you updated once it’s available.

**Comment by lucemia** [comment]
@abingham 

I’ve just released a mirror package with a different module name to avoid conflicts with ffmpeg-python.

To install the package, use:

    pip install typed-ffmpeg-compatible

When using the compatible package, simply change your import ffmpeg statement to:

    import typed_ffmpeg

Please let me know if you encounter any issues.

**Comment by abingham** [comment]
Thanks! This seems to work.
