### ISSUE TITLE
Example of how to use lavfi

### ISSUE THREAD

**Issue by abingham** [lucemia/typed-ffmpeg#403]
Are there any examples of how to use lavfi? I'm porting some code from `ffmpeg-python` to `typed-ffmpeg`, and I can't get the parts using lavfi to work. For example, how would I do something like `ffmpeg-python` invocation in `typed-ffmpeg`?:
```python
red = ffmpeg.input("color=c=red:s=100x100", format="lavfi", r=30)
```

**Comment by lucemia** [comment]
The `format` keyword argument in ffmpeg-python is an alias for `f`, which is the original argument name in ffmpeg. Therefore, in typed-ffmpeg, you can use f to achieve the same functionality.

ref: 
- https://ffmpeg.org/ffmpeg.html#Main-options
- https://github.com/kkroening/ffmpeg-python/blob/df129c7ba30aaa9ffffb81a48f53aa7253b0b4e6/ffmpeg/_ffmpeg.py#L29-L31

```
>>> import ffmpeg
>>> import typed_ffmpeg
>>> ffmpeg.input("color=c=red:s=100x100", format="lavfi", r=30).output('tmp').compile()
['ffmpeg', '-f', 'lavfi', '-r', '30', '-i', 'color=c=red:s=100x100', 'tmp']  # in ffmpeg-python, `-format` auto translate to `-f`

>>> typed_ffmpeg.input("color=c=red:s=100x100", f="lavfi", r=30).output(filename='tmp').compile()
['ffmpeg', '-f', 'lavfi', '-r', '30', '-i', 'color=c=red:s=100x100', 'tmp']
```

**Comment by abingham** [comment]
Ah, thanks for clearing that up.

**Comment by abingham** [comment]
Also, I just wanted to say thanks for creating this project. ffmpeg-python seems to be dead, but I really do need something like it. typed-ffmpeg does an excellent job. And also thanks for being an engaged and supportive maintainer!

**Comment by lucemia** [comment]
Thank you so much for the kind words! I’m glad to hear that typed-ffmpeg is useful for your project. It’s still fairly new, so any feedback or suggestions you have are more than welcome! I really appreciate your support and engagement.
